"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { formatINR, getCategories, getVendors, Vendor, VendorCategory } from "../lib/vendors";

function VendorCard({ vendor }: { vendor: Vendor }) {
  return <article className="group overflow-hidden rounded-2xl border border-[#f0ded8] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg">
    <img src={vendor.avatarUrl || "/weddingpic.jpg"} alt={`${vendor.businessName} profile`} className="h-48 w-full object-cover" />
    <div className="p-5"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-wider text-[#8B000F]">{vendor.category?.name || "Event vendor"}</p>{vendor.approvalStatus === "approved" && <span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">Approved</span>}</div><h3 className="mt-2 text-xl font-bold text-[#6b1839]">{vendor.businessName}</h3><p className="mt-1 text-sm text-slate-600">{[vendor.city, vendor.state].filter(Boolean).join(", ") || "Bihar"}</p><p className="mt-3 text-sm font-semibold text-slate-800">From {formatINR(vendor.priceFromMinor)}</p><Link href={`/customer/vendor?slug=${encodeURIComponent(vendor.slug)}`} className="mt-5 inline-flex rounded-lg bg-[#8B000F] px-4 py-2 text-sm font-semibold text-white transition hover:bg-[#6b000f] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#8B000F] focus-visible:ring-offset-2">View vendor</Link></div>
  </article>;
}

export default function Home() {
  const [categories, setCategories] = useState<VendorCategory[]>([]);
  const [vendors, setVendors] = useState<Vendor[]>([]);
  const [query, setQuery] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([getCategories(), getVendors({})]).then(([categoryData, vendorData]) => { setCategories(categoryData.categories); setVendors(vendorData.vendors.slice(0, 3)); }).catch(() => setError("We could not load marketplace highlights right now.")); }, []);
  return <div className="bg-[#fffdfc]">
    <section className="overflow-hidden bg-gradient-to-br from-[#fff0f3] via-[#fffaf8] to-[#ffe6d8]"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-16 lg:grid-cols-[1.1fr_.9fr] lg:py-24"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#8B000F]">Eventra Bihar</p><h1 className="mt-4 font-serif text-4xl font-bold tracking-tight text-[#5c1632] sm:text-5xl lg:text-6xl">Your celebration deserves the right team.</h1><p className="mt-6 text-lg leading-8 text-slate-700">Explore approved wedding and event vendors across Bihar, compare real services, and send a booking request in a few simple steps.</p><form action="/services" className="mt-8 flex flex-col gap-3 rounded-2xl bg-white p-3 shadow-lg sm:flex-row"><label className="sr-only" htmlFor="home-search">Search vendors</label><input id="home-search" name="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try photographers, venues, makeup artists…" className="min-w-0 flex-1 rounded-xl border border-[#e7d4ce] px-4 py-3 outline-none focus:border-[#8B000F] focus:ring-2 focus:ring-[#8B000F]/20" /><button className="rounded-xl bg-[#8B000F] px-6 py-3 font-semibold text-white hover:bg-[#6b000f]">Browse vendors</button></form><div className="mt-6 flex flex-wrap gap-3"><Link href="/services" className="rounded-lg border border-[#8B000F] bg-white px-5 py-3 font-semibold text-[#8B000F] hover:bg-[#fff7f3]">Explore all vendors</Link><Link href="/vendor" className="rounded-lg px-5 py-3 font-semibold text-[#8B000F] underline underline-offset-4">Become a vendor</Link></div></div><img src="/weddingpic.jpg" alt="Wedding celebration" className="h-72 w-full rounded-3xl object-cover shadow-xl lg:h-full" /></div></section>
    <section className="mx-auto max-w-7xl px-6 py-16"><div className="flex items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#8B000F]">Browse by need</p><h2 className="mt-2 font-serif text-3xl font-bold text-[#5c1632]">Popular categories</h2></div><Link href="/services" className="text-sm font-semibold text-[#8B000F] underline underline-offset-4">View all vendors</Link></div>{error ? <p className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</p> : <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{categories.length ? categories.map((category) => <Link key={category.slug} href={`/services?category=${encodeURIComponent(category.slug)}`} className="rounded-2xl border border-[#f0ded8] bg-white p-5 font-semibold text-[#6b1839] shadow-sm transition hover:border-[#d89b86] hover:shadow-md">{category.name}<span className="mt-2 block text-sm font-normal text-slate-600">Find local specialists</span></Link>) : <p className="col-span-full rounded-xl border border-dashed border-[#e7d4ce] p-6 text-slate-600">Categories will appear here when available.</p>}</div>}</section>
    <section className="bg-[#fff7f3]"><div className="mx-auto max-w-7xl px-6 py-16"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#8B000F]">Marketplace highlights</p><h2 className="mt-2 font-serif text-3xl font-bold text-[#5c1632]">Featured approved vendors</h2><div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{error ? null : vendors.length ? vendors.map((vendor) => <VendorCard key={vendor.id} vendor={vendor} />) : <p className="rounded-xl border border-dashed border-[#e7d4ce] bg-white p-6 text-slate-600">No approved vendors are available yet.</p>}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-16"><h2 className="font-serif text-3xl font-bold text-[#5c1632]">A simpler way to plan</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{[["1", "Find", "Search vendors by category and city."], ["2", "Compare", "Review real services and starting prices."], ["3", "Request", "Send your event details to a vendor."], ["4", "Track", "Check your request status in My Bookings."]].map(([number, title, description]) => <div key={number} className="rounded-2xl border border-[#f0ded8] bg-white p-6"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#fff0f3] font-bold text-[#8B000F]">{number}</span><h3 className="mt-4 font-bold text-[#6b1839]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></div>)}</div></section>
  </div>;
}
